### PR TITLE
Add number

### LINKED ISSUE #2: Add-number.js
- [ ] develop and test ```addNumbers.js```

### PR DESCRIPTION
**Pull request by oguzkarademir**

### CODE REVIEW

**Review by pavelbidenko2018 — APPROVED** [review]
@oguzkarademir Thank you for a adding wireframe into dev-strategy.
All other seems also fine

**Review by Sayed94h — COMMENTED** [review]
Hi @oguzkarademir  I reviewed your codes. These look ok but I am not 100% sure because I am not good at reviewing others code for now and I need more practice. I am not going to merge your pull request because there are also two other reviewers to review and approve your codes. I think the guy should merge the pull request who is 100% sure about the codes. 

Greetings 

Sayed

**Review by okozmovskaya — COMMENTED** [review]
The script looks clear and perfect. May be I understood something wrong, but when I enter the number return the console: "All saved numbers: undefined". The handler Add number finish the handler Display number and Display number-handler contain the comment: "// this handler works, no ned to change it.  Just to study it!". I thought that display should show me the number, which I added. May be there is mistakes in the template or my pull?

**Comment by oguzkarademir** [comment]
> Hi @oguzkarademir I reviewed your codes. These look ok but I am not 100% sure because I am not good at reviewing others code for now and I need more practice. I am not going to merge your pull request because there are also two other reviewers to review and approve your codes. I think the guy should merge the pull request who is 100% sure about the codes.
> 
> Greetings
> 
> Sayed

👍

**Comment by oguzkarademir** [comment]
> The script looks clear and perfect. May be I understood something wrong, but when I enter the number return the console: "All saved numbers: undefined". The handler Add number finish the handler Display number and Display number-handler contain the comment: "// this handler works, no ned to change it. Just to study it!". I thought that display should show me the number, which I added. May be there is mistakes in the template or my pull?

@okozmovskaya there is a part to be written in `display-array.js`,  @pavelbidenko2018 will write the logic

**Comment by okozmovskaya** [comment]
> > The script looks clear and perfect. May be I understood something wrong, but when I enter the number return the console: "All saved numbers: undefined". The handler Add number finish the handler Display number and Display number-handler contain the comment: "// this handler works, no ned to change it. Just to study it!". I thought that display should show me the number, which I added. May be there is mistakes in the template or my pull?
> 
> @okozmovskaya there is a part to be written in `display-array.js`, @pavelbidenko2018 will write the logic

Yes, you are right, I didn't see the beginning of script

**Comment by okozmovskaya** [comment]
> > > The script looks clear and perfect. May be I understood something wrong, but when I enter the number return the console: "All saved numbers: undefined". The handler Add number finish the handler Display number and Display number-handler contain the comment: "// this handler works, no ned to change it. Just to study it!". I thought that display should show me the number, which I added. May be there is mistakes in the template or my pull?
> > 
> > 
> > @okozmovskaya there is a part to be written in `display-array.js`, @pavelbidenko2018 will write the logic
> 
> Yes, you are right, I didn't see the beginning of script

**Review by okozmovskaya — APPROVED** [review]

**Pull request merged**
